<?php
include_once("library/include_files.php");

$REQ_SEND[PARAM_USERID] = "";
$REQ_SEND[PARAM_TOPICID] = "";
$REQ_SEND[PARAM_SUBTOPICID] = "";
$REQ_SEND[PARAM_POSTID] = "";
$REQ_SEND[PARAM_CONTENT] = "";
$REQ_SEND[PARAM_FOR_DISCUSSION] = "";
$REQ_SEND[PARAM_ACTION] = "";

if(isset ($_SESSION['login']['user_id'])) {
	$REQ_SEND[PARAM_USERID] = $_SESSION['login']['user_id'];
}
if(isset ($_REQUEST[PARAM_TOPICID])) {
	$REQ_SEND[PARAM_TOPICID] = $_REQUEST[PARAM_TOPICID];
}
if(isset ($_REQUEST[PARAM_SUBTOPICID])) {
	$REQ_SEND[PARAM_SUBTOPICID] = $_REQUEST[PARAM_SUBTOPICID];
}
if(isset ($_REQUEST[PARAM_POSTID])) {
	$REQ_SEND[PARAM_POSTID] = $_REQUEST[PARAM_POSTID];
}
if(isset ($_REQUEST[PARAM_CONTENT])) {
	$REQ_SEND[PARAM_CONTENT] = $_REQUEST[PARAM_CONTENT];
}
if(isset ($_REQUEST[PARAM_FOR_DISCUSSION])) {
	$REQ_SEND[PARAM_FOR_DISCUSSION] = $_REQUEST[PARAM_FOR_DISCUSSION];
}if(isset ($_REQUEST['dd'])) {
	$REQ_SEND[PARAM_FOR_DISCUSSION] = $_REQUEST['dd'];
}
if(isset ($_REQUEST[PARAM_ACTION])) {
	$REQ_SEND[PARAM_ACTION] = $_REQUEST[PARAM_ACTION];
}

if(isset ($_REQUEST['dd'])) {
	$REQ_SEND[PARAM_FOR_DISCUSSION] = $_REQUEST['dd'];
	$REQ_SEND[PARAM_ACTION] = "viewed";
}

$ObjCURL = new INIT_PROCESS(DISCUSSION_SERVICE_PAGE, $REQ_SEND);
$result = $ObjCURL->response;

print $result;
?>
